### PR TITLE
feat: remove colon from getFormattedAddress

### PR DESCRIPTION
**Pull request by JoFlo07**
Hi Daniel! 
I encountered that when I am creating a vCard (version 3.0) that in the address section an extra colon was added. I removed it from the getFormattedAdress-Function and it seems to work out well now. 
Let me know if you have any doubts.

Cheers and thanks for the great package.

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
Hi Florian, 
thanks for the first contribution to this package!

It seems like the `:` is specified in the [RFC6350](https://tools.ietf.org/html/rfc6350#section-6.3.1) (see the example) and I couldn't find any examples where it is omitted.
Do you have one, so I can comprehend where the problem is?

**Comment by JoFlo07** [comment]
Hi Daniel! I create a short code snippet on stackblitz to reproduce the error. You will see that when you download the vCard there is an empty linke and an extra colon in the address field. If you, however, remove this colon from the getFormattedAddress Function, it won't appear. Hope it helps.

https://stackblitz.com/edit/angular-ivy-cbp4zi

**Comment by DanielHabenicht** [comment]
Ahh, okay now I get it. (I always had other values in front like `TYPE`)

But it seems like there are might be even more colons :D 
I will update the PR tomorrow and then merge it. Thanks again!
- [ ] Add test for case without basic properties (e.g. Type) 
- [ ] Remove double colons: 
https://github.com/DanielHabenicht/ngx-vcard/blob/f9e2dac454ea4872b1d712ede723ea32e7aa3790/projects/ngx-vcard/src/lib/ngx-vcard.formatter.ts#L116
https://github.com/DanielHabenicht/ngx-vcard/blob/f9e2dac454ea4872b1d712ede723ea32e7aa3790/projects/ngx-vcard/src/lib/ngx-vcard.formatter.ts#L263-L264

**Comment by DanielHabenicht** [comment]
Closing in favour for #340. I have mentioned you in the commit. 
Thanks again!

**Pull request closed without merging**
